from django.db import models
from .tablas.tipodocumento import TipoDocumento
from .tablas.curso import Curso
from .tablas.profesor import Profesor
from .tablas.estudiantes import Estudiantes
from .tablas.clase import Clase
from .tablas.asistencia import Asistencia
from .tablas.evaluacion import Evaluacion
from .tablas.nota import Nota